from sentence_transformers import SentenceTransformer, util
import numpy as np
import torch
from beam import env
import os

class TextSimilarity:
    def __init__(self, model_name='all-MiniLM-L6-v2', device='cpu'):
        """
        Initializes the TextSimilarity class with a specified SentenceTransformer model and device.
        
        :param model_name: The name of the pre-trained model to use for generating embeddings.
                           Default is 'all-MiniLM-L6-v2'.
        :param device: The device to run the model on ('cpu' or 'cuda'). Default is 'cpu'.
        """
        self.device = device
        
        # Set environment variable to force eager attention implementation
        os.environ["TRANSFORMERS_ATTENTION_IMPLEMENTATION"] = "eager"
        
        if env.is_remote():
            if model_name.startswith("/"):
                self.model = SentenceTransformer(model_name,  device=self.device)
            else:
                self.model = SentenceTransformer(model_name,  device=self.device,cache_folder="/volumes/model-weights/model-weigths/")
        else:
            self.model = SentenceTransformer(model_name, device=self.device)
        
        # After loading your SentenceTransformer model:
        try:
        
            self.model[0].auto_model.config.attn_implementation = "eager"
            self.model[0].auto_model.config.output_attentions = True
        except Exception as e:
            print(f"Warning: Could not set attention configuration: {e}")

    def encode_text(self, text):
        """
        Encodes a given text into an embedding vector using the SentenceTransformer model.
        
        :param text: The input text to encode.
        :return: A normalized numpy array representing the embedding of the input text.
        """
        # Encode the text and convert the tensor to a numpy array
        embedding = self.model.encode(text, convert_to_tensor=True, device=self.device)
        embedding = embedding.cpu().numpy()  # Convert tensor to numpy array
        # Normalize the embedding to unit length
        embedding = embedding / np.linalg.norm(embedding)
        return embedding

    def find_similar(self, query_text, corpus, top_k=5):
        """
        Finds the most similar texts in a corpus to a given query text based on cosine similarity.
        
        :param query_text: The text for which similar texts are to be found.
        :param corpus: A list of texts against which the query text will be compared.
        :param top_k: The number of top similar texts to return. Default is 5.
        :return: A list of tuples containing the similar texts and their similarity scores.
        """
        # Encode the query text and corpus as numpy arrays
        query_embedding = self.encode_text(query_text)
        print(query_embedding.shape)
        corpus_embeddings = self.encode_text(corpus)

        # Compute cosine similarities between the query embedding and all corpus embeddings
        cosine_scores = util.pytorch_cos_sim(torch.tensor(query_embedding), torch.tensor(corpus_embeddings))[0]

        # Get the top-k most similar texts
        top_results = np.argpartition(-cosine_scores, range(top_k))[:top_k]

        # Return the top-k similar texts and their cosine scores
        similar_texts = [(corpus[idx], float(cosine_scores[idx])) for idx in top_results]
        similar_texts = sorted(similar_texts, key=lambda x: x[1], reverse=True)

        return similar_texts
    


# Example usage
if __name__ == "__main__":
    # Initialize the TextSimilarity class
    text_similarity = TextSimilarity(model_name="/Users/tolgagunduz/Documents/projects/blushyv2/scripts/output/match_fine_tuned_model")

    # Define a query text
    query = """
    this is a black leggings. the leggings features a black tone with solid pattern. this modern, sleek leggings is made from likely a synthetic material with a slight sheen with a high-waisted, form-fitting, full-length fit. perfect for evening out, casual date, this black leggings the leggings are shown on a model standing still, highlighting their fit and shape.. notable features include criss-cross waist design, slight sheen. ideal for fall, winter, spring. suitable for mild weather weather. follows modern minimalist trends. perfect for night out, casual. these black high-waisted leggings feature a unique criss-cross design at the waist, creating a flattering and stylish silhouette.  the fabric appears to have a subtle sheen, suggesting a sleek, possibly slightly stretchy material. the leggings are form-fitting, hugging the legs from the high waist to the ankles. they are shown paired with a cropped top and heeled sandals, suggesting a look suitable for a night out or a more dressed-up casual occasion. the length is full-length, covering the entire leg. 
   """
    # Define a corpus of texts
    corpus = """this is a black leggings. the leggings features a black tone with mottled pattern. this casual leggings is made from likely a soft, stretchy blend such as cotton or a cotton-polyester mix with a slim fit, ankle length fit. perfect for casual, this black leggings the leggings are shown on a model standing in a relaxed pose, showcasing the fit and drape of the fabric.. notable features include subtle mottled texture, slim fit. ideal for autumn, spring. suitable for mild weather weather. follows minimalist trends. perfect for everyday wear, casual outings. these black leggings feature a subtle mottled texture, adding depth and visual interest to a classic style.  the slim fit hugs the legs, creating a streamlined silhouette. the leggings appear to be made from a soft, stretchy fabric, offering both comfort and style. they extend to the ankles, providing full coverage. the image shows them worn with sneakers, suggesting a casual and versatile look. 
this is a black leggings. the leggings features a black tone with snakeskin embossed pattern. this casual chic leggings is made from likely a polyester blend for stretch and sheen with a high-waisted, slim fit, form-fitting fit. perfect for casual wear, this black leggings the leggings are shown on a model standing, highlighting the fit and drape of the fabric.. notable features include high waist, snakeskin embossed pattern. ideal for autumn, spring. suitable for mild weather weather. follows animal print trends. perfect for casual outings, errands, or paired with a dressy top for a night out. these high-waisted leggings feature a snakeskin embossed pattern on a sleek, black base. the fabric appears to have a subtle sheen, suggesting a potentially smooth and stretchy material.  the leggings are shown fitted to the model's legs, indicating a slim, form-fitting design. the high waist provides a flattering silhouette and offers good coverage. the image showcases the leggings from the side, highlighting the fit and the subtle texture of the snakeskin pattern.  they appear comfortable and suitable for various activities. 
this is a black leggings. the leggings features a black tone with solid pattern. this athleisure leggings is made from likely a blend of performance fabrics like polyester and spandex with a high-waisted, full-length, form-fitting fit. perfect for workout, casual wear, this black leggings the model is wearing the leggings, showcasing their fit and shape.. notable features include high waist. ideal for all seasons. suitable for versatile weather. follows athleisure trends. perfect for workout, casual. these black high-waisted leggings have a sleek, form-fitting silhouette.  the fabric looks smooth and possibly has a slight sheen.  the high waist provides a flattering fit and offers good coverage.  the leggings are shown extending to the ankles, suggesting a full-length design.  they appear to be made from a comfortable, stretchy material suitable for both athletic and casual wear. the seams are clean and subtle, contributing to the overall streamlined look. 
this is a black leggings. the leggings features a black tone with solid pattern. this casual leggings is made from faux leather with a slim, fitted fit. perfect for casual wear, this black leggings the leggings are worn under an oversized shirt, showcasing their slim fit and smooth texture.. notable features include faux leather finish, slim fit. these black leggings have a sleek, faux leather finish. they are full-length, reaching the ankles, and appear to have a slim, fitted silhouette. the fabric looks smooth and has a slight sheen, characteristic of faux leather. the leggings are plain, without any visible pockets or embellishments. they are a versatile wardrobe staple that can be styled in various ways. 
this is a burgundy, deep red leggings. the leggings features a burgundy, deep red tone with solid pattern. this casual leggings is made from likely a synthetic blend, possibly polyester or nylon, with a smooth texture. with a slim, form-fitting, full-length fit. perfect for casual wear, athleisure, this burgundy, deep red leggings the leggings are shown in a static pose, highlighting their fit and drape.. notable features include solid color, smooth texture, form-fitting. ideal for autumn, winter, spring. suitable for cool to mild weather weather. follows minimalist, athleisure trends. perfect for everyday wear, casual outings, athletic activities. these are solid-color leggings, designed for a close-to-body fit.  the image shows a side profile, highlighting the smooth, form-fitting nature of the garment.  they appear to be made from a stretchy, possibly synthetic material, and extend from the waist to the ankle. the lack of visible seams or details suggests a minimalist design. the length appears to be full-length, suitable for various heights. the fabric drapes smoothly against the leg, indicating a comfortable and flexible material. 
this is a black leggings. the leggings features a black tone with none pattern. this athletic/casual leggings is made from stretchy polyester blend with a none fit. perfect for activewear, this black leggings none. notable features include no unique features. 
this is a black leggings. the leggings features a black tone with solid pattern. this sporty chic leggings is made from faux leather with a fitted, high-waisted fit. perfect for everyday wear, this black leggings the model is standing, showcasing the fit and drape of the leggings.. notable features include high waist, smooth faux-leather texture. high-waisted, black leggings with a smooth, faux-leather texture. the leggings have a fitted silhouette, hugging the legs closely. they appear to be made of a stretchy material, providing a comfortable fit. the high waistline accentuates the figure, creating a flattering look. the leggings are a versatile piece that can be styled in various ways, making them suitable for a range of occasions. 
this is a white leggings. the leggings features a white tone with solid pattern. this minimalist leggings is made from likely a cotton-spandex blend with a high-waisted, form-fitting, full-length fit. perfect for casual wear, this white leggings the leggings are shown on a model standing still, highlighting their fit and drape.. notable features include high waist, simple design, solid color. ideal for all seasons. suitable for suitable for most weather conditions, especially as a base layer in colder weather weather. follows minimalist trends. perfect for everyday wear, layering. these are simple, solid white leggings. they appear to be made from a soft, stretchy material, possibly a blend of cotton and spandex. the leggings have a high waist and a close-fitting, form-hugging silhouette that follows the body's natural shape.  they extend from the waist to the ankles, providing full leg coverage. the image shows a smooth, even texture with no visible seams or embellishments. the leggings are shown on a model, suggesting a comfortable and flexible fit. 
this is a black leggings. the leggings features a black tone with solid with lace detail pattern. this casual chic leggings is made from likely a soft, stretchy knit fabric with a slim-fitting, full-length leggings fit. perfect for casual, this black leggings the leggings are shown on a model standing, highlighting the fit and the lace detail.. notable features include side lace panel, subtle contrast between solid and sheer fabric. ideal for autumn, spring. suitable for mild weather weather. follows lace details trends. perfect for everyday wear, casual outings. these black leggings feature a unique design detail: a sheer lace panel running down the side of each leg. the lace is a dark black, creating a subtle contrast against the solid black leggings. the leggings appear to be made from a soft, stretchy fabric, providing both comfort and a flattering fit.  the image shows the leggings on a model, showcasing how they hug the legs without being overly tight. the lace panel adds a touch of femininity and visual interest to a classic wardrobe staple. 
this is a black leather leggings. the leather leggings features a black tone with solid pattern. this modern, minimalist leather leggings is made from faux leather with a high-waisted, slim fit, full length fit. perfect for casual outings, nights out, this black leather leggings the model's pose highlights the leggings' fit and how they drape.. notable features include high-waisted, leather-like material, slim fit. ideal for autumn, spring, winter. suitable for cool to cold weather weather. follows leather trend trends. perfect for casual. these black leather leggings offer a sleek and modern look.  the high-waisted design is flattering and elongates the legs. the fabric appears to have a subtle sheen, suggesting a smooth, possibly faux leather material. the leggings are form-fitting, creating a streamlined silhouette. they are paired with a zebra print top and ankle boots in the image, demonstrating a versatile styling option. the leggings appear comfortable and flexible, suitable for various activities. 
this is a light blue, white leggings. the leggings features a light blue, white tone with subtle camouflage pattern. this sporty leggings is made from seamless, stretchy fabric (likely a blend of nylon and spandex) with a high-waisted, form-fitting, full-length fit. perfect for workout, errands, casual outings, this light blue, white leggings the leggings are shown in a static pose, highlighting their fit and design.. notable features include seamless construction, subtle camouflage pattern. ideal for spring/summer/autumn. suitable for mild weather weather. follows athleisure trends. perfect for athletic wear, casual wear. these light blue seamless leggings feature a subtle camouflage pattern woven into the fabric.  the high-waisted design offers a flattering fit, while the form-fitting silhouette hugs the legs.  the fabric appears to be a soft, stretchy material, ideal for athletic activities or casual wear.  the leggings are shown in a straight-on pose, highlighting the streamlined design and the subtle texture of the fabric. the pattern is not overly bold, allowing the leggings to be versatile enough for various outfits. 
this is a black, white leggings. the leggings features a black, white tone with stripe pattern. this sporty casual leggings is made from ribbed, stretchy fabric (likely a blend of cotton and/or polyester) with a slim, form-fitting, full-length fit. perfect for workout, running errands, this black, white leggings the leggings are shown on a model standing, showcasing the fit and drape of the fabric.. notable features include contrasting white stripe. ideal for spring/summer/autumn. suitable for mild weather weather. follows sporty, athleisure trends. perfect for casual wear, athletic activities. these are women's black leggings featuring a sporty design with a contrasting white stripe running down the side. the leggings appear to be made from a ribbed, stretchy fabric, suggesting comfort and flexibility.  the fit is slim and form-fitting, hugging the legs closely. the image shows the leggings cuffed at the ankle, suggesting they are full-length. the side stripe adds a visual detail that breaks up the solid black color, creating a modern and athletic look. the fabric looks smooth and relatively thin, suitable for warmer weather. 
this is a dark black leggings. the leggings features a dark black tone with none pattern. this athletic casual leggings is made from stretchy polyester blend with a none fit. perfect for activewear, this dark black leggings none. notable features include no unique features. 
this is a black leather leggings. the leather leggings features a black tone with solid pattern. this modern chic leather leggings is made from faux leather with a high-waisted, slim fit, ankle-length fit. perfect for night out, this black leather leggings the leggings are shown on a model standing still, highlighting the fit and drape of the fabric.. notable features include high-waisted, slim fit, faux leather material. ideal for autumn, winter, spring. suitable for mild to cool weather weather. follows minimalist, modern trends. perfect for evening out, casual wear, date night. these black faux leather leggings offer a sleek and modern look.  the high-waisted design provides a flattering silhouette, while the slim fit hugs the legs for a streamlined appearance. the leggings are crafted from a smooth, supple faux leather material that has a subtle sheen.  they appear comfortable and stretchy, suitable for various body types. the image shows the leggings worn with black heels, suggesting a polished and sophisticated style. 
this is a blue leggings. the leggings features a blue tone with solid pattern. this sporty leggings is made from soft, stretchy fabric with a high-waisted, form-fitting, full-length fit. perfect for workout, casual, this blue leggings the model is standing still, showcasing the leggings' fit and shape.. notable features include high waist, ribbed detailing, full-length. ideal for spring, summer, autumn. suitable for warm weather weather. follows athleisure trends. perfect for workout, casual. high-waisted leggings with a flattering, form-fitting silhouette. the ribbed detailing along the sides adds a touch of visual interest and texture.  the fabric appears to be a soft, stretchy material that moves with the body. the leggings are shown in a relaxed pose, highlighting their comfortable fit and sleek design.  they feature a high waist for comfortable coverage and a full-length design for versatile styling. 
this is a black leggings. the leggings features a black tone with solid pattern. this modern, sleek leggings is made from likely a synthetic material with a slight sheen with a high-waisted, form-fitting, full-length fit. perfect for evening out, casual date, this black leggings the leggings are shown on a model standing still, highlighting their fit and shape.. notable features include criss-cross waist design, slight sheen. ideal for fall, winter, spring. suitable for mild weather weather. follows modern minimalist trends. perfect for night out, casual. these black high-waisted leggings feature a unique criss-cross design at the waist, creating a flattering and stylish silhouette.  the fabric appears to have a subtle sheen, suggesting a sleek, possibly slightly stretchy material. the leggings are form-fitting, hugging the legs from the high waist to the ankles. they are shown paired with a cropped top and heeled sandals, suggesting a look suitable for a night out or a more dressed-up casual occasion. the length is full-length, covering the entire leg. 
this is a black leather leggings. the leather leggings features a black tone with solid pattern. this modern, chic leather leggings is made from faux leather with a high-waisted, slim fit, leggings fit. perfect for night out, this black leather leggings the leggings are shown on a model standing, showcasing the fit and drape of the garment.. notable features include high-waisted, faux leather material, slim fit. ideal for fall, winter, spring. suitable for mild to cool weather weather. follows minimalist, modern trends. perfect for casual outings, nights out, date nights. these black faux leather leggings offer a sleek and modern look.  the high-waisted design provides a flattering silhouette, while the slim fit hugs the legs for a streamlined appearance. the smooth, slightly textured surface of the faux leather gives the leggings a luxurious feel.  the leggings are shown in a close-up shot, highlighting the material's texture and the subtle sheen.  they appear comfortable and stretchy, suitable for various occasions. 
this is a black leggings. the leggings features a black tone with solid pattern. this casual leggings is made from ribbed knit with a high-waisted, form-fitting, full-length fit. perfect for casual outings, errands, workouts, this black leggings the leggings are shown on a model standing still, showcasing their fit and drape.. notable features include high waist, ribbed texture. ideal for autumn,winter,spring. suitable for mild weather weather. follows minimalist trends. perfect for everyday wear, athleisure. these black high-waisted leggings offer a sleek and comfortable fit.  the fabric appears to have a subtle ribbed texture, adding visual interest. the leggings are form-fitting, hugging the legs from the high waist to the ankles.  in the image, they appear to be made from a stretchy material that drapes smoothly against the body. the length is full-length, ending at the ankles.  they seem ideal for layering or wearing on their own for a casual yet polished look. 
this is a black leggings. the leggings features a black tone with zebra print pattern. this sporty chic leggings is made from textured, stretchy fabric (likely a blend of polyester and spandex) with a high-waisted, form-fitting, full-length fit. perfect for workout, errands, casual outings, this black leggings the leggings are shown on a model standing, showcasing the fit and drape of the fabric.. notable features include high waist, subtle zebra print, textured fabric. ideal for fall, winter, spring. suitable for cool weather weather. follows athleisure trends. perfect for athletic activities, casual wear. these black leggings feature a high-waisted design that sits comfortably at the natural waistline. the fabric is a sleek, textured material with a subtle zebra-like pattern that adds visual interest without being overpowering.  the leggings are form-fitting, hugging the legs closely for a streamlined silhouette. they appear to be made from a stretchy, comfortable material suitable for both athletic activities and casual wear. the length extends to the ankles, and the overall fit is flattering and versatile. 
this is a white leggings. the leggings features a white tone with solid pattern. this casual leggings is made from likely a cotton blend or similar soft material with a slim, form-fitting fit. perfect for casual wear, this white leggings the leggings are worn straight, showcasing their slim fit and length.. notable features include solid color, slim fit. ideal for spring/summer/fall. suitable for mild weather weather. follows minimalist trends. perfect for everyday wear. these are solid white leggings with a slim, form-fitting silhouette. they appear to be made from a soft, stretchy material that hugs the legs comfortably. the leggings extend from the waist to the ankles, creating a sleek and streamlined look.  the fabric looks smooth and has a subtle sheen. they are shown paired with a light blue denim shirt and brown sandals, demonstrating their versatility for casual outfits. 
this is a black leggings. the leggings features a black tone with solid pattern. this minimalist leggings is made from likely a soft, stretchy blend of materials such as nylon and spandex with a high-waisted, form-fitting, full-length fit. perfect for casual wear, this black leggings the leggings are shown on a model standing in a relaxed pose, highlighting the smooth fit and drape of the fabric.. notable features include high-waisted, form-fitting, full-length. ideal for autumn, winter, spring. suitable for cool to mild weather weather. follows minimalist, versatile trends. perfect for everyday wear, casual outings, layering under dresses or skirts. these are high-waisted leggings that offer a sleek and comfortable fit. the fabric appears to be a soft, stretchy material, providing a smooth silhouette against the body.  the leggings extend from the high waist to the ankles, with a close-fitting, form-hugging design. the image shows the leggings draped smoothly over the legs, suggesting a comfortable and flexible feel. the hemline is a simple, clean finish, without any visible embellishments or detailing. the leggings appear to be opaque, providing full coverage. the overall look is minimalist and versatile, suitable for layering or wearing on their own. 
this is a black leggings. the leggings features a black tone with solid pattern. this modern minimalist leggings is made from faux leather with a slim, fitted, high-waisted, ankle-length fit. perfect for casual outings, nights out, this black leggings the leggings are shown fitted to the legs, highlighting their sleek and form-fitting design.. notable features include faux leather material, high-waisted, slim fit. ideal for fall/winter, spring. suitable for mild to cool weather weather. follows minimalist, modern trends. perfect for casual, dressy casual. these black faux leather leggings have a slim, fitted silhouette that hugs the legs. they appear to be made from a smooth, supple material that provides a sleek look. the leggings are high-waisted, creating a flattering shape and providing comfortable coverage. the length is ankle-length, showing a bit of the wearer's footwear. the leggings are shown paired with a light blue shirt and heels, suggesting a versatile style. 
this is a navy, teal leggings. the leggings features a navy, teal tone with a subtle ombre pattern. this casual sporty leggings is made from a stretchy poly-spandex blend with a mid-rise, form-fitting, 7/8 length fit. perfect for running errands or light workouts, this navy, teal leggings the leggings are shown in a standing pose, highlighting the ombre gradient that transitions from navy at the waist to teal near the calves.. notable features include comfortable waistband, soft ombre effect. ideal for spring, summer. suitable for mild weather weather. follows athleisure trends. perfect for everyday wear or light exercise. these ombre leggings provide a smooth, seamless transition between two shades, creating a visually appealing look. the material appears soft yet supportive, with clean seams and a comfortable stretch that adapts to various movements.
this is a charcoal gray, white leggings. the leggings features a charcoal gray tone with mesh panel accents in white. this active leggings is made from a breathable nylon-spandex blend with a high-waisted, slim fit, ankle length fit. perfect for gym sessions, yoga classes, this charcoal gray, white leggings the leggings are shown with the mesh panels strategically placed around the calves, offering ventilation and style.. notable features include mesh paneling, supportive waistband. ideal for spring/summer. suitable for mild to warm weather weather. follows modern activewear trends. perfect for workout, athleisure. these leggings boast a sleek, high-waisted design that contours the waist, while the mesh inserts add both breathability and a fashionable twist.
this is a olive green leggings. the leggings features a olive green tone with ribbed texture pattern. this casual chic leggings is made from likely a cotton-blend with a mid-rise, slim fit, full-length fit. perfect for everyday wear, this olive green leggings the leggings are worn with a tucked-in tank top, emphasizing the ribbed vertical lines that visually elongate the legs.. notable features include ribbed fabric, soft stretch. ideal for autumn, spring. suitable for mild weather weather. follows minimalist trends. perfect for casual outings, layering. these ribbed leggings have a comfortable, moderate stretch that retains its shape, making them a versatile piece for both lounging and stepping out.
this is a taupe leggings. the leggings features a taupe tone with a suede-like texture pattern. this casual chic leggings is made from a microfiber blend with a mid-rise, tapered, full-length fit. perfect for coffee dates, errands, this taupe leggings the leggings are worn in a relaxed pose, showing the soft suede-like finish and subtle stitching.. notable features include plush texture, comfortable stretch. ideal for autumn, winter. suitable for cooler weather weather. follows cozy-luxe trends. perfect for everyday wear. these leggings have a gentle, velvety surface that mimics suede, adding a luxurious touch without compromising flexibility or comfort.
this is a dark plum leggings. the leggings features a dark plum tone with solid pattern. this athletic leggings is made from a seamless nylon-spandex knit with a high-waisted, full-length, compression fit. perfect for intense workouts, this dark plum leggings the leggings are shown in a dynamic pose, suggesting flexibility and support.. notable features include wide ribbed waistband, seamless construction. ideal for autumn, spring. suitable for mild weather weather. follows high-performance activewear trends. perfect for gym, running, yoga. these seamless leggings offer targeted compression around the waist and thighs, promoting muscle support and a flattering silhouette.
""".split("\n")

    # Find similar texts
    similar_texts = text_similarity.find_similar(query, corpus, top_k=20)

    # Print the results
    print(f"Query: {query}")
    print("Similar texts to the query:")
    for line,(text, score) in zip(corpus,similar_texts):
        if line[:100]!=text[:100]:
            print("#",f"Text--> (Score: {score:.4f}) {text[:100]} ")
        else:
            print(f"Text--> (Score: {score:.4f}) {text[:100]} ")